[package]
name = "gitguardian-client"
version = "0.1.0"
edition = "2024"

[features]
default = ["ureq"]
reqwest = ["dep:reqwest", "dep:futures-core"]
ureq = ["dep:ureq"]

[dependencies]
gitguardian-api = { path = "../gitguardian-api" }
bytes = "1"
futures-core = { version = "0.3", optional = true }
http = "1"
thiserror = "2"
reqwest = { version = "0.13", default-features = false, features = [
    "rustls",
], optional = true }
ureq = { version = "3", optional = true }

[dev-dependencies]
gitguardian-mock = { path = "../gitguardian-mock" }
futures-util = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
